export let elements = {
	ticSide: document.querySelector(".tic-side"),
	tacSide: document.querySelector(".tac-side"),
	ticScore: document.querySelector(".tic-score"),
	tacScore: document.querySelector(".tac-score"),
	gameBoard: document.querySelector(".game-board"),
	spot: document.querySelector(".spot"),
	turn: document.querySelector(".turn"),
	spot1: document.querySelector("#spot1"),
	spot2: document.querySelector("#spot2"),
	spot3: document.querySelector("#spot3"),
	spot4: document.querySelector("#spot4"),
	spot5: document.querySelector("#spot5"),
	spot6: document.querySelector("#spot6"),
	spot7: document.querySelector("#spot7"),
	spot8: document.querySelector("#spot8"),
	spot9: document.querySelector("#spot9"),
	result: document.querySelector(".result"),
	resetButton: document.querySelector(".reset-button"),
};
